# Generated by Django 3.2.2 on 2021-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
